version: "3.7"
services:
  app:
    build:
      args:
        user: Wla
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ticketing
    container_name: ticketing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ticketing
  db:
    image: mysql:8.0
    container_name: ticketing-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - ticketing
  nginx:
    image: nginx:1.17-alpine
    container_name: ticketing-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - ticketing
networks:
  ticketing:
    driver: bridge
volumes:
  dbdata:
    driver: local
